sudo: required
language: ruby
rvm:
  - 2.2.3
services:
  - docker
env:
  - NAME=${TRAVIS_REPO_SLUG:15} COMMIT=${TRAVIS_COMMIT:0:7}
before_install:
  - gem install bundler
  - bundle install
  - docker login -e="${HUB_EMAIL}" -u="${HUB_USERNAME}" -p="${HUB_PASSWORD}"
  - docker pull solinea/"${NAME}":latest || true
install:
  - docker build -t "${NAME}" .
before_deploy:
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    "${DOCKER_REGISTRY}"
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    "${DOCKER_REGISTRY_DEV}"
deploy:
  - provider: script
    script: hack/bin/push-images-release
    on:
      tags: true
  - provider: script
    script: hack/bin/push-images-master
    on:
      branch: master
notifications:
  email: false
  slack:
    secure: G6ZwClgFOJo28gFFl6QM+QDEWGQbq6Fsq+LrMf2gu8hRdMzJLaNn13PBwaT8FOx81wjFQVJL3q+9bUS3Q8DNaET7AyWGIALTr++TF1wumirR9RVcD/dKP9NMJU0hguvtklzt2KnHS7HPXpQUN6pOhOR5g47UmRBtKePycTo+3i+mUZnX7OtPpRzq3nbei7TjIeWpjgPUmGgiFW0zwTeQy4ZGZH6F1UpjhgZK+qdkpDtfNuTYnV8f///n8g4CvEYMjmkXNd4lBJQIs465wWyRYPBUXF5a0HnGb2Y+k3Ng5CTz6TIu5bUhDv1fLShvDKRtGbpliMi2RayfptGx0HQNFzMFDfRyG9GdQvjEg0ZSDbrWqG9j3vudr3tkaP9waIbUflufY0I7oUmnrGsgEi7zw0brQr/GZnCasbh5Dj5DhfYo2862Dfl/Md7nXvoJMQthctmI/T0v+7pNDIxBqTJCj0+oK3dPtzfdrSAyECZQHlS61ertUqbaHcfhKFvg426Nc/zcWVjf+gHRNXN/qn47Bukedstd6KyIaU0rfRWFaq6Ko6pcd0EEmJQj0PKUJ4ZiPc8kSHvYgzn9pViP4nYFcqEyJ+ESToRmTHhR1pkELMwkArfQLldPg8eS0JVrRPntFOMer0fzMai5ZMPjIpmOAF4L0Dd97qgb32uUWY4MGIk=
